package org.armman.sakhi.data.rules

/**
 * `risk_conditions` primary keys required as the `conditionIds` input to the ANC/Infant
 * clinical-risk-grading GoRules packs ([RuleSetIds.RISK_ANC] / [RuleSetIds.RISK_INFANT]).
 *
 * Both packs throw if a condition code they try to record is missing from this map (see
 * `record(...)`/`gradeNutritionField(...)` in `anc-risk.rulesJson.ts` /
 * `infant-risk.rulesJson.ts`) — this is non-form, caller-injected data, not something either
 * graph resolves on its own.
 *
 * ⚠ **Not fixed across environments**, unlike [RuleSetIds]. These are `risk_conditions.id`
 * values generated by `@default(uuid())` at seed time in `risk-referral-service` — dev's values
 * (below, confirmed against dev 2026-08-24) do not carry over to SIT/UAT/prod. Re-export this map
 * per environment before shipping anywhere beyond dev.
 */
object RiskConditionIds {
  /** Condition codes for [RuleSetIds.RISK_ANC] (mother/ANC visit-form risk grading). */
  val ANC: Map<String, String> = mapOf(
    "AGE" to "a8900106-38dc-4c05-8a6e-3635cbf5d43d",
    "ANEMIA" to "5c44f875-6e06-41b9-be89-81ce3cb388ad",
    "APH" to "45d0790b-9184-4c92-a724-e827242149e0",
    "BAD_OBSTETRIC_HISTORY" to "087b5a14-b19e-45be-b846-f0e378d07314",
    "DANGER_SIGNS" to "5a8e6965-136a-4ed3-b10e-11c0d1e7b219",
    "FETAL_HEART_RATE" to "7a4d6290-31da-427b-97de-4177d9cba126",
    "FUNDAL_HEIGHT" to "804dcd28-a971-4ad8-8884-871d21b8899f",
    "GESTATIONAL_WEIGHT_GAIN" to "a947b486-1bd8-4095-b32e-6c4cda1ae76a",
    "HYPERGLYCEMIA" to "d49bf99a-32b7-41b2-b63c-af883a357740",
    "HYPERTENSION" to "d885e0c7-a276-4f98-8fdc-62d0542ddf4f",
    "HYPERTHERMIA" to "6884bddf-5f9d-4c80-bdb7-657f44675100",
    "HYPOGLYCEMIA" to "55f2590f-e538-4f18-8d49-068c6d8e4d46",
    "HYPOTENSION" to "95fd4244-98bc-4516-b99f-06347f7a896b",
    "HYPOTHERMIA" to "8112afa7-41b3-4074-b39a-cb08e0aaae90",
    "JAUNDICE" to "91c7bafb-b24e-4888-9a1c-38914b9eeb0b",
    // ANC/maternal STUNTING (phase ANC, entityType MOTHER) — distinct from the infant pack's
    // STUNTING_STATUS (phase INC, entityType CHILD) below. Do not conflate the two codes.
    "MUAC_BMI" to "b6b1bd62-4ab4-490a-a205-164fed2fc3d1",
    "PPH" to "025ccb52-5f70-442b-8473-e95727c1a520",
    "STUNTING" to "47bdc156-2246-4a55-9975-45a9ce0ffd98",
    "URINE_ANALYSIS" to "fbe85ea2-45e8-44ad-b73a-6976fb8c1f1a",
  )

  /** Condition codes for [RuleSetIds.RISK_INFANT] (infant/neonatal visit-form risk grading). */
  val INFANT: Map<String, String> = mapOf(
    "CORD_INFECTION" to "585a9a23-4f67-4ee8-9125-d1c2a3a71ea4",
    "FEEDING_ADEQUACY" to "a8e72eac-37b4-4cf0-95b7-222b33fa25ce",
    "INFANT_DANGER_SIGNS" to "ea2805b8-6291-47c8-a1b4-cf76a24c35d5",
    "INFANT_HYPERTHERMIA" to "40fb8b2c-1bf5-4bd3-a806-23b188c66c67",
    "INFANT_HYPOTHERMIA" to "b65b63fa-6b58-4d61-8f71-bee09f9954c6",
    "LOW_BIRTH_WEIGHT" to "67b63080-aff3-440a-9c07-76c30f698712",
    "MUAC_MALNUTRITION" to "39f7cda7-866e-4a23-a6ef-b3c70c5b4f3b",
    "NEURO_DEVELOPMENTAL_STATUS" to "7ecdd6e0-f474-4618-b5ed-86be31b9be4b",
    "RESPIRATORY_DISTRESS" to "c9cf1981-6f23-4b8e-8ac4-fbae65a5d998",
    "STUNTING_STATUS" to "e8231dd6-6a03-4467-b3e9-2d406d63a6eb",
    "UNDERWEIGHT" to "0c6a20ea-f136-4780-9147-2321cc4ecdf9",
    "WASTING" to "cbd97eea-4b88-4a02-a041-8b143da07bd5",
  )
}
